### PR TITLE
Notify about failed dependency updates

### PR DESCRIPTION
**Pull request by danielsdeleo**
* If triggered via slack, always reply to the user with the error
* Use simple rate limiting to ensure the team channel is only notified
  about failures once per hour.

### CODE REVIEW

**Comment by mwrock** [comment]
I'm assuming this is running on a jenkins slave. Instead of using a file, it might be easier to use an environment variable. Still not incredibly well versed in jenkins, but the only downside here is I think your have to set the variable per project.

**Comment by danielsdeleo** [comment]
The failures in this case are when running `rake dependencies` fails. For example, it was failing yesterday because it lists the versions from `current`, but when you promote the package is removed from `current`, so the latest current was behind and a sanity check failed. This doesn't concern when an actual jenkins build for dependencies fails, I have a separate ticket in the backlog to poll the dependency update builds and check for failures. Tl;dr, this is running inside the lita bot and not on jenkins.

**Comment by mwrock** [comment]
gotcha :+1:

**Comment by tyler-ball** [comment]
👍

**Pull request merged**
